# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Disable VFS file watching on Windows to prevent file lock errors in .gradle/caches/transforms
org.gradle.vfs.watch=false

# AndroidX support
android.useAndroidX=true

# Kotlin Daemon
kotlin.daemon.jvm.options=-Xmx1536m
